[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 
Referrer-Policy ="no-referrer-when-downgrade"
    Feature-Policy = "payment 'none' "
    X-Content-Type-Options = "nosniff"
    
    
    [[redirects]]
  from = "https://drrahulvaghelamusic.netlify.com"
  to = "https://www.drrahulvaghelamusic.com"
  status = 200
  force = true

RewriteCond %{HTTP_USER_AGENT} ^-?$
RewriteCond %{REQUEST_URI} !^(.*)(/feed)(.*)$
RewriteRule ^ - [F]
